const ZNCA_PLATFORM = 'Android';
const ZNCA_PLATFORM_VERSION = '8.0.0';
const ZNCA_VERSION = '2.2.0';
const ZNCA_USER_AGENT = `com.nintendo.znca/${ZNCA_VERSION}(${ZNCA_PLATFORM}/${ZNCA_PLATFORM_VERSION})`;
const ZNCA_CLIENT_ID = '71b963c1b7b6d119';

module.exports = {
    ZNCA_PLATFORM,
    ZNCA_PLATFORM_VERSION,
    ZNCA_VERSION,
    ZNCA_USER_AGENT,
    ZNCA_CLIENT_ID
}